openapi: 3.0.2
info:
  title: Basware OAUTH2 authentication APIs AccountingDocuments UserGroups API
  description: "**Using OAUTH2.0 authentication:**\n\nGet API access token from api.basware.com/tokens\n1. Using client id and client secret, which you can obtain from Basware. \n2. Specify which APIs can be accessed by using the token e.g. Read only access to vendors API only (these are called scopes). Available scopes are listed at <https://developer.basware.com/api/p2p/manual#AccessRights>. \n3. Each token has an expiration time, until which it can be used to call APIs.\n\nWhen using OAUTH2 authentication, you need to pass the OAUTH2 authentication token when calling Basware API endpoints. Available Basware API operations are documented at <https://api.basware.com/swagger>. \n\nSee the Basware API developer site at <https://developer.basware.com/api/p2p/manual#Authentication> for more details on API authentication."
  version: 1.0.0
  x-logo:
    url: https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png
tags:
- name: UserGroups
paths:
  /v1/userGroups/{externalCode}:
    get:
      tags:
      - UserGroups
      summary: Returns user group by externalCode
      parameters:
      - name: externalCode
        in: path
        description: The ExternalCode of the entity to be fetched
        required: true
        schema:
          type: string
      - name: x-amz-meta-continuationToken
        in: header
        description: Used to get next page of results when item count indicated by 'pageSize' is exceeded. A token is returned in header (not body) parameter 'X-amz-meta-continuationToken' of the response whenever there are more records to fetch. Post the received value here in a new HEADER parameter on the next GET request to receive the next page of results. When getting the next page of results, you must include the same query parameters that were used when getting the first page.
        schema:
          type: string
        example: 7a71f046-4450-47b1-9ee9-8af480f5be1b
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/userGroups:
    get:
      tags:
      - UserGroups
      summary: Returns a list of available user groups.
      parameters:
      - name: OrganizationExternalCode
        in: query
        schema:
          type: string
      - name: x-amz-meta-continuationToken
        in: header
        description: Used to get next page of results when item count indicated by 'pageSize' is exceeded. A token is returned in header (not body) parameter 'X-amz-meta-continuationToken' of the response whenever there are more records to fetch. Post the received value here in a new HEADER parameter on the next GET request to receive the next page of results. When getting the next page of results, you must include the same query parameters that were used when getting the first page.
        schema:
          type: string
        example: 4ef57cfb-145c-4e44-9337-ff363180c1c1
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - UserGroups
      summary: Create or update user group
      parameters:
      - name: Content-Type
        in: header
        description: Specifies the media type of the resource. Value application/json is supported.
        schema:
          type: string
        example: application/json
      requestBody:
        description: The user groups to create or update.
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserGroup'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserGroup'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserGroup'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserGroup'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserGroup'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
            application/json:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
            text/json:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
      - UserGroups
      summary: Delete user groups
      description: "For manual one-time operations only, such as a manual clean-up to remove test data generated during API integration development. Only removes records from API layer. \r\nDeletion in target systems needs to be done separately using the data deletion mechanisms available in each of the target system in addition to deleting the data in Basware API."
      requestBody:
        description: "Contains the body of the request.\r\n            Either externalCode or lastUpdated -field is required. If both values are provided, externalCode will have the priority."
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/DeleteDataRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteDataRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/DeleteDataRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DeleteDataRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '400':
          description: BadRequest
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
            application/json:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
            text/json:
              schema:
                $ref: '#/components/schemas/IModelValidationResult'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '202':
          description: RequestAccepted
        '500':
          description: Unexpected error
components:
  schemas:
    DeleteResponse:
      type: object
      properties:
        statusApiLink:
          type: string
          description: Gets or sets the API link to check the status of the delete operation.
          nullable: true
        taskName:
          type: string
          description: Gets or sets the name of the delete task.
          nullable: true
        taskStatus:
          type: string
          description: Gets or sets the current status of the delete task.
          nullable: true
          readOnly: true
        statusEnum:
          $ref: '#/components/schemas/BulkOperationStatus'
      additionalProperties: false
      description: Represents the response returned after a delete operation.
    BulkOperationStatus:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: Represents the possible statuses of a bulk operation.
      format: int32
    IModelValidationResult:
      type: object
      properties:
        requestId:
          type: string
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/IModelValidationError'
          nullable: true
          readOnly: true
        hasErrors:
          type: boolean
          readOnly: true
      additionalProperties: false
    IModelValidationError:
      type: object
      properties:
        code:
          type: string
          nullable: true
        externalCode:
          type: string
          nullable: true
        info:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        cdmErrorMappingOrganizationCode:
          type: string
          nullable: true
      additionalProperties: false
    UserGroup:
      required:
      - externalCode
      - name
      - organizationExternalCode
      type: object
      properties:
        externalCode:
          maxLength: 100
          minLength: 1
          type: string
          description: Unique identifier for the user group. Used to identify the user group when it is updated.
          example: IND_Admins
        name:
          maxLength: 100
          minLength: 1
          type: string
          description: Name of the user group
          example: India Admins
        description:
          maxLength: 250
          minLength: 0
          type: string
          description: Description of the user group
          nullable: true
          example: Group for India admin users
        organizationExternalCode:
          maxLength: 100
          minLength: 1
          type: string
          description: ExternalCode identifier for the organization on which the user group resides.
          example: BW10
      additionalProperties: false
      description: "Represents a user group within an organization, including its unique identifier,\r\nname, description, and associated organization information."
    DeleteDataRequest:
      type: object
      properties:
        externalCode:
          maxLength: 36
          minLength: 0
          type: string
          description: Single item can be deleted using externalCode and final status is returned immediately.
          nullable: true
        lastUpdated:
          type: string
          description: 'To delete records updated after specific time, use lastUpdated -field. This will delete all items that have been updated after the specified date. In response, user will get the taskStatus api link where the task status can be checked. Note: ''0001-01-01'' can be used to delete all records.'
          format: date-time
          nullable: true
      additionalProperties: false
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
