openapi: 3.0.2
info:
  title: Basware OAUTH2 authentication APIs AccountingDocuments Companies (deprecated) API
  description: "**Using OAUTH2.0 authentication:**\n\nGet API access token from api.basware.com/tokens\n1. Using client id and client secret, which you can obtain from Basware. \n2. Specify which APIs can be accessed by using the token e.g. Read only access to vendors API only (these are called scopes). Available scopes are listed at <https://developer.basware.com/api/p2p/manual#AccessRights>. \n3. Each token has an expiration time, until which it can be used to call APIs.\n\nWhen using OAUTH2 authentication, you need to pass the OAUTH2 authentication token when calling Basware API endpoints. Available Basware API operations are documented at <https://api.basware.com/swagger>. \n\nSee the Basware API developer site at <https://developer.basware.com/api/p2p/manual#Authentication> for more details on API authentication."
  version: 1.0.0
  x-logo:
    url: https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png
tags:
- name: Companies (deprecated)
paths:
  /v1/companies:
    get:
      tags:
      - Companies (deprecated)
      summary: Returns companies posted to Basware API.
      description: ''
      parameters:
      - name: pageSize
        in: query
        description: A limit for the number of items to be returned for one request. Limit can range between 1 and 500 items.
        schema:
          type: integer
          format: int32
          default: 500
      - name: lastUpdated
        in: query
        description: Date Filter. Returns items that have been updated after specified date.
        schema:
          type: string
          format: date-time
      - name: x-amz-meta-continuationtoken
        in: header
        description: Used to get next page of results when item count indicated by 'pageSize' is exceeded. A token is returned in header (not body) parameter 'X-amz-meta-continuationToken' of the response whenever there are more records to fetch. Post the received value here in a new HEADER parameter on the next GET request to receive the next page of results. When getting the next page of results, you must include the same query parameters that were used when getting the first page.
        schema:
          type: string
        example: 181e100d-88ea-4e60-a183-06eacc69334d
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CompanyResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CompanyResponse'
        '401':
          description: Unauthorized
        '404':
          description: Not found. Request was successful and no records were found.
        '500':
          description: Unexpected error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
    post:
      tags:
      - Companies (deprecated)
      summary: Creates new companies, fully overwrites previous record if exists.
      description: "Note: Only consuming target system at the moment is Open Network Portal (incl. Vendor manager). Companies cannot be imported to P2P through this API. \r\n\r\nPlease see section \"[Usage scenario 6: Import companies](https://developer.basware.com/api/p2p/manual#usage6)\" of Basware Purchase-to-Pay API manual for details on implementing this API."
      parameters:
      - name: Content-Type
        in: header
        description: Specifies the media type of the resource. Value application/json is supported.
        schema:
          type: string
        example: application/json
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CompanyEntity'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CompanyEntity'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CompanyEntity'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CompanyEntity'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompanyEntity'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompanyEntity'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompanyEntity'
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
        '401':
          description: Unauthorized
        '409':
          description: Conflict
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
        '500':
          description: Unexpected error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
  /v1/companies/{companyCode}:
    get:
      tags:
      - Companies (deprecated)
      summary: Returns single company record by companyCode - identifier.
      description: ''
      parameters:
      - name: companyCode
        in: path
        description: The companyCode of the entity to be fetched
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CompanyEntity'
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyEntity'
            text/json:
              schema:
                $ref: '#/components/schemas/CompanyEntity'
        '401':
          description: Unauthorized
        '404':
          description: Not found. Request was successful and no records were found.
        '500':
          description: Unexpected error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseEntityList'
components:
  schemas:
    CompanyEntity:
      required:
      - active
      - companyCode
      - name
      type: object
      properties:
        companyCode:
          maxLength: 32
          minLength: 1
          type: string
          description: Unique code to identify the company. Also used as an 'externalCode' for the company.
          example: '200'
        sourceSystem:
          maxLength: 32
          minLength: 1
          type: string
          description: Informative name of the source system, e.g. ERP instance.
          nullable: true
          example: SAP_1
        name:
          maxLength: 100
          minLength: 1
          type: string
          description: Company name.
          example: Acme corporation
        description:
          maxLength: 250
          minLength: 0
          type: string
          description: Company description.
          nullable: true
          example: ''
        lastUpdated:
          type: string
          description: Timestamp when the record was last sent to API. Set automatically.
          format: date-time
        bucompid:
          maxLength: 36
          minLength: 1
          type: string
          description: Basware internal ID for the company. Generated by Basware API.
          nullable: true
          example: c61f8a6f-140f-423b-b9fd-3ae32345febb
        identifiers:
          type: array
          items:
            $ref: '#/components/schemas/CompanyIdentifierEntity'
          description: 'Company identifiers. See "[Usage scenario 6: Import companies](https://developer.basware.com/api/p2p/manual#usage6) on Basware API developer site for explanation of available values.'
          nullable: true
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/CompanyAddressEntity'
          description: Company addresses.
          nullable: true
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/CompanyContactEntity'
          description: Company contacts.
          nullable: true
        userDefaultLanguage:
          maxLength: 25
          minLength: 0
          type: string
          description: "The default language code for users for this company. \r\nUse following format: [language 2-chars in UPPERCASE]-[country 2-chars in lowercase]."
          nullable: true
          example: en-US
        homeCurrency:
          maxLength: 3
          minLength: 3
          type: string
          description: Company home currency.
          nullable: true
          example: EUR
        active:
          type: boolean
          description: Determines is company active or inactive. It is also used for soft delete.
          example: true
        publishToBusinessDirectory:
          type: boolean
          description: When 'true, the company data entity will be published to Business Directory in Basware Portal.
          nullable: true
          example: true
      additionalProperties: false
    CompanyIdentifierEntity:
      required:
      - id
      - schemeId
      type: object
      properties:
        id:
          maxLength: 36
          minLength: 1
          type: string
          description: Company identifier value.
          example: GB190101452
        schemeId:
          maxLength: 36
          minLength: 1
          type: string
          description: "Company identifier type. Defines type of ‘Id’ -field. Available values:\r\nDUNS, EMAIL-RFC2822, GLN, IBAN, ISO6523-ACTORID-UPIS, UNKNOWN, EU:VAT, AT:ORGNR, AU:ABN, AU:ACN, AU:TFN, BE:KBO, CA:BN, CA:GST, CA:VAT, CH:ORGNR, CH:VAT, CN:BRN, CZ:ORGNR, DE:ORGNR, DK:CVR, EE:ORGNR, ES:CIF, ES:NIF, FI:Y-TUNNUS, FR:SIRENE, FR:SIRET, GB:UTR, IE:ORGNR, IN:GSTIN, IT:FISCALE, IT:IPA, LI:VAT, MX:VAT, MY:GST, NL:KVK, NO:ORGNR, NO:VAT, PL:KRS, PL:REGON, PT:NIF, SE:ORGNR, SK:ORGNR, GB:ORGNR, UstidNr, US:TIN"
          example: EU:VAT
      additionalProperties: false
    CompanyContactEntity:
      required:
      - name
      - role
      type: object
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
          description: Name of the contact. Used as a key in list of contacts.
          example: DeliveryContact1
        description:
          maxLength: 200
          minLength: 0
          type: string
          nullable: true
          example: Use this as a primary contact
        telephone:
          maxLength: 50
          minLength: 0
          type: string
          description: Specifies the contact's telephone number.
          nullable: true
          example: 555-3342-454
        telefax:
          maxLength: 50
          minLength: 0
          type: string
          description: Specifies the contact's fax number.
          nullable: true
          example: 555-3342-45412
        email:
          maxLength: 200
          minLength: 0
          type: string
          description: Specifies the contact's email address.
          nullable: true
          example: mrsmith@business.org
        website:
          maxLength: 200
          minLength: 0
          type: string
          description: Specifies the contact's web site address.
          nullable: true
          example: www.mrSmith.com
        role:
          enum:
          - AdditionalContact
          - PrimaryContact
          - SecondaryContact
          type: string
          description: Role of contact.
      additionalProperties: false
    ErrorEntity:
      type: object
      properties:
        externalCode:
          type: string
          description: External code of record on which error occurred (when available).
          nullable: true
          example: 4847-31231212-212121-1212
        type:
          enum:
          - BUSINESS
          - VALIDATION
          - TECHNICAL
          - SECURITY
          type: string
          description: Error type.
          example: ''
        code:
          enum:
          - EXTERNAL_CODE_MISMATCH
          - SCHEMA_VALIDATION_ERROR
          - CONFLICT_IN_POST
          - DATA_ORIGIN_VALIDATION_ERROR
          - ACCESS_TOKEN_VALIDATION_ERROR
          - CREDENTIAL_VALIDATION_ERROR
          - PARAMETER_VALIDATION_ERROR
          - UNEXPECTED_ERROR
          - METHOD_NOT_ALLOWED
          - ENTITY_NOT_FOUND
          - DATA_VALIDATION_FAILED
          - SNS_PUBLISH_ERROR
          - SQS_PUBLISH_ERROR
          type: string
          description: Error code.
          example: ''
        message:
          type: string
          description: Specific error message.
          nullable: true
          example: ''
        info:
          type: string
          description: Information about type of the error.
          nullable: true
          example: ''
      additionalProperties: false
    CompanyAddressEntity:
      required:
      - addressType
      - externalCode
      - name
      type: object
      properties:
        externalCode:
          maxLength: 36
          minLength: 1
          type: string
          description: External code for company address.
          example: d6437eef-0d71-4cb0-8a6e-7f114831479d
        name:
          maxLength: 200
          minLength: 1
          type: string
          description: Specifies the address' name for the company.
          example: Remittance address
        description:
          maxLength: 200
          minLength: 0
          type: string
          nullable: true
          example: This is used as Remit To address
        addressType:
          enum:
          - AdditionalAddress
          - VisitingAddress
          - RemittanceAddress
          - DeliveryAddress
          - PostalAddress
          - RegistrationAddress
          - InvoicingAddress
          type: string
          description: 'Specifies type of the address. Types supported by P2P: DeliveryAddress, InvoicingAddress, PostalAddress.'
          example: DeliveryAddress
        addressLine1:
          maxLength: 200
          minLength: 0
          type: string
          description: Company address as free text, line 1.
          nullable: true
          example: 1800 Main Street
        addressLine2:
          maxLength: 200
          minLength: 0
          type: string
          description: Company address as free text, line 2.
          nullable: true
        addressLine3:
          maxLength: 200
          minLength: 0
          type: string
          description: Company address as free text, line 3.
          nullable: true
        cityName:
          maxLength: 50
          minLength: 0
          type: string
          description: City name.
          nullable: true
          example: Dallas
        postalZone:
          maxLength: 50
          minLength: 0
          type: string
          description: Postal zone.
          nullable: true
          example: '75201'
        poBox:
          maxLength: 50
          minLength: 0
          type: string
          description: PO box.
          nullable: true
          example: '724'
        streetName:
          maxLength: 50
          minLength: 0
          type: string
          description: Street name.
          nullable: true
          example: Burlington Avenue
        locality:
          maxLength: 50
          minLength: 0
          type: string
          description: Attribute to postalAddress. This field is required in UK if a similar road name exists within a post town area.
          nullable: true
          example: Burlington
        countrySubEntity:
          maxLength: 50
          minLength: 0
          type: string
          description: Country sub entity.
          nullable: true
          example: TX
        countrySubEntityDescription:
          maxLength: 50
          minLength: 0
          type: string
          description: Country sub entity description.
          nullable: true
          example: Texas
        countryId:
          maxLength: 2
          minLength: 2
          type: string
          description: Defines the country ID for the company.
          nullable: true
          example: US
        default:
          type: boolean
          description: Is this the default address (true / false).
          nullable: true
      additionalProperties: false
    CompanyResponse:
      required:
      - companies
      type: object
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/CompanyEntity'
      additionalProperties: false
    ResponseEntityList:
      type: object
      properties:
        requestId:
          type: string
          description: ID of the request on which error occurred (generated by Basware API).
          nullable: true
          example: fbc082a2-65a4-469c-b230-d84a252f18fc
        hasErrors:
          type: boolean
          description: Specifies whether the request has errors.
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorEntity'
          nullable: true
      additionalProperties: false
      description: Errors returned here are returned synchronously from Basware API middle layer. Additional errors coming from target system(s) may be returned through errorFeedbacks API.
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
